### ISSUE TITLE
Cannot import EDL

### ISSUE THREAD

**Issue by dimitarsp** [tin2tin/import_edl#4]
Hi, I am trying to import an EDL exported from Davinci Resolve. When trying to import into Blender, I get the following error:

```
Python: Traceback (most recent call last):
  File "addons\import_edl\__init__.py", line 116, in execute
    if not elist.parse(filepath, dummy_fps):
  File "addons\import_edl\parse_edl.py", line 565, in parse
    if tot_m2 == -1:
UnboundLocalError: local variable 'tot_m2' referenced before assignment

location: <unknown location>:-1
```

Attached is the EDL that I am trying to import renamed to txt to be able to import here
[02.txt](https://github.com/tin2tin/import_edl/files/6555708/02.txt)

I've tried in 2.92 official, 2.93 beta, and 3.0 alpha and get the same error in all three

**Comment by tin2tin** [comment]
There is a newer add-on for importing and exporting timelines in Blender here: https://gitlab.com/superprod/stax_suite/vse-io

**Comment by tin2tin** [comment]
I don't know what this is: 
`M2   AX             076.2                00:02:44:04`
And I do not know if this is supported(I only updated the add-on). 

Try to remove all of those lines manually and try importing it again.
